// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
	CreateBookcasePostData,
	CreateBookcasePostErrors,
	CreateBookcasePostResponses,
	CreateBookPostData,
	CreateBookPostErrors,
	CreateBookPostResponses,
	CreateShelfPostData,
	CreateShelfPostErrors,
	CreateShelfPostResponses,
	DeleteBookcaseDeleteData,
	DeleteBookcaseDeleteErrors,
	DeleteBookcaseDeleteResponses,
	DeleteBookDeleteData,
	DeleteBookDeleteErrors,
	DeleteBookDeleteResponses,
	DeleteShelfDeleteData,
	DeleteShelfDeleteErrors,
	DeleteShelfDeleteResponses,
	GetBookByIsbnGetData,
	GetBookByIsbnGetErrors,
	GetBookByIsbnGetResponses,
	ReadBookcaseGetData,
	ReadBookcaseGetErrors,
	ReadBookcaseGetResponses,
	ReadBookcasesWithCountsGetData,
	ReadBookcasesWithCountsGetResponses,
	ReadBookGetData,
	ReadBookGetErrors,
	ReadBookGetResponses,
	ReadBooksGetData,
	ReadBooksGetErrors,
	ReadBooksGetResponses,
	ReadShelfGetData,
	ReadShelfGetErrors,
	ReadShelfGetResponses,
	ReadShelvesGetData,
	ReadShelvesGetErrors,
	ReadShelvesGetResponses,
	RootGetData,
	RootGetResponses,
	UpdateBookcasePatchData,
	UpdateBookcasePatchErrors,
	UpdateBookcasePatchResponses,
	UpdateBookPatchData,
	UpdateBookPatchErrors,
	UpdateBookPatchResponses,
	UpdateShelfPatchData,
	UpdateShelfPatchErrors,
	UpdateShelfPatchResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Read Bookcases With Counts
 *
 * Retrieve all bookcases with a count of shelves and books per shelf.
 */
export const readBookcasesWithCountsGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadBookcasesWithCountsGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<ReadBookcasesWithCountsGetResponses, unknown, ThrowOnError>({
		url: '/api/bookcases/',
		...options
	});

/**
 * Create Bookcase
 *
 * Create a new bookcase.
 */
export const createBookcasePost = <ThrowOnError extends boolean = false>(
	options: Options<CreateBookcasePostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		CreateBookcasePostResponses,
		CreateBookcasePostErrors,
		ThrowOnError
	>({
		url: '/api/bookcases/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Delete Bookcase
 *
 * Delete a bookcase.
 */
export const deleteBookcaseDelete = <ThrowOnError extends boolean = false>(
	options: Options<DeleteBookcaseDeleteData, ThrowOnError>
) =>
	(options.client ?? client).delete<
		DeleteBookcaseDeleteResponses,
		DeleteBookcaseDeleteErrors,
		ThrowOnError
	>({ url: '/api/bookcases/{bookcase_id}', ...options });

/**
 * Read Bookcase
 *
 * Retrieve a single bookcase by its ID with its shelves.
 */
export const readBookcaseGet = <ThrowOnError extends boolean = false>(
	options: Options<ReadBookcaseGetData, ThrowOnError>
) =>
	(options.client ?? client).get<ReadBookcaseGetResponses, ReadBookcaseGetErrors, ThrowOnError>({
		url: '/api/bookcases/{bookcase_id}',
		...options
	});

/**
 * Update Bookcase
 *
 * Update a bookcase's details.
 */
export const updateBookcasePatch = <ThrowOnError extends boolean = false>(
	options: Options<UpdateBookcasePatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<
		UpdateBookcasePatchResponses,
		UpdateBookcasePatchErrors,
		ThrowOnError
	>({
		url: '/api/bookcases/{bookcase_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Read Shelves
 *
 * Retrieve a list of shelves.
 */
export const readShelvesGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadShelvesGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<ReadShelvesGetResponses, ReadShelvesGetErrors, ThrowOnError>({
		url: '/api/shelves/',
		...options
	});

/**
 * Create Shelf
 *
 * Create a new shelf.
 */
export const createShelfPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateShelfPostData, ThrowOnError>
) =>
	(options.client ?? client).post<CreateShelfPostResponses, CreateShelfPostErrors, ThrowOnError>({
		url: '/api/shelves/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Delete Shelf
 *
 * Delete a shelf.
 */
export const deleteShelfDelete = <ThrowOnError extends boolean = false>(
	options: Options<DeleteShelfDeleteData, ThrowOnError>
) =>
	(options.client ?? client).delete<
		DeleteShelfDeleteResponses,
		DeleteShelfDeleteErrors,
		ThrowOnError
	>({ url: '/api/shelves/{shelf_id}', ...options });

/**
 * Read Shelf
 *
 * Retrieve a single shelf by its ID with its books.
 */
export const readShelfGet = <ThrowOnError extends boolean = false>(
	options: Options<ReadShelfGetData, ThrowOnError>
) =>
	(options.client ?? client).get<ReadShelfGetResponses, ReadShelfGetErrors, ThrowOnError>({
		url: '/api/shelves/{shelf_id}',
		...options
	});

/**
 * Update Shelf
 *
 * Update a shelf's details.
 */
export const updateShelfPatch = <ThrowOnError extends boolean = false>(
	options: Options<UpdateShelfPatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<UpdateShelfPatchResponses, UpdateShelfPatchErrors, ThrowOnError>(
		{
			url: '/api/shelves/{shelf_id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		}
	);

/**
 * Read Books
 *
 * Retrieve a list of books.
 */
export const readBooksGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadBooksGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<ReadBooksGetResponses, ReadBooksGetErrors, ThrowOnError>({
		url: '/api/books/',
		...options
	});

/**
 * Create Book
 *
 * Create a new book, along with authors and categories if they don't exist.
 */
export const createBookPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateBookPostData, ThrowOnError>
) =>
	(options.client ?? client).post<CreateBookPostResponses, CreateBookPostErrors, ThrowOnError>({
		url: '/api/books/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Delete Book
 *
 * Delete a book.
 */
export const deleteBookDelete = <ThrowOnError extends boolean = false>(
	options: Options<DeleteBookDeleteData, ThrowOnError>
) =>
	(options.client ?? client).delete<
		DeleteBookDeleteResponses,
		DeleteBookDeleteErrors,
		ThrowOnError
	>({ url: '/api/books/{book_id}', ...options });

/**
 * Read Book
 *
 * Retrieve a single book by its ID.
 */
export const readBookGet = <ThrowOnError extends boolean = false>(
	options: Options<ReadBookGetData, ThrowOnError>
) =>
	(options.client ?? client).get<ReadBookGetResponses, ReadBookGetErrors, ThrowOnError>({
		url: '/api/books/{book_id}',
		...options
	});

/**
 * Update Book
 *
 * Update a book's details.
 */
export const updateBookPatch = <ThrowOnError extends boolean = false>(
	options: Options<UpdateBookPatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<UpdateBookPatchResponses, UpdateBookPatchErrors, ThrowOnError>({
		url: '/api/books/{book_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Get Book By Isbn
 *
 * gets book info by isbn
 */
export const getBookByIsbnGet = <ThrowOnError extends boolean = false>(
	options: Options<GetBookByIsbnGetData, ThrowOnError>
) =>
	(options.client ?? client).get<GetBookByIsbnGetResponses, GetBookByIsbnGetErrors, ThrowOnError>({
		url: '/api/isbn/{isbn}',
		...options
	});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
	options?: Options<RootGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
		url: '/',
		...options
	});
